// ── Game styles ───────────────────────────────────────────────

export const S = {
  root: {
    display: "flex",
    width: "100vw",
    height: "100dvh",
    fontFamily: "'Nunito', sans-serif",
    background: "#0e4525",
    overflow: "hidden",
    position: "relative",
  },
  felt: {
    position: "absolute",
    inset: 0,
    background:
      "radial-gradient(ellipse at 60% 50%, #1e7d46 0%, #145c33 60%, #0e4525 100%)",
    zIndex: 0,
  },

  // ── Sidebar ──
  sidebar: {
    width: 240,
    minWidth: 240,
    background: "#1a2340",
    borderRight: "3px solid #0d1829",
    display: "flex",
    flexDirection: "column",
    zIndex: 2,
  },
  blindHeader: {
    background: "#2a6fd4",
    padding: "7px 12px",
    textAlign: "center",
    borderBottom: "3px solid #1a4fa0",
  },
  blindTitle: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 9,
    color: "#fff",
    letterSpacing: 1,
  },
  blindInfo: {
    padding: "8px 10px",
    borderBottom: "2px solid #0d1829",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  blindBadge: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: "#2a4fa0",
    border: "2px solid #4a7ad4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 5,
    color: "#fff",
    textAlign: "center",
    flexShrink: 0,
    lineHeight: 1.4,
  },
  scoreLabel: { fontSize: 10, color: "#8a9bc0", fontWeight: 700 },
  scoreTarget: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 14,
    color: "#e63946",
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  rewardText: { fontSize: 10, color: "#8a9bc0", marginTop: 2 },
  rewardVal: { color: "#ffd700", fontWeight: 900 },

  roundScoreRow: {
    padding: "7px 12px",
    borderBottom: "2px solid #0d1829",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rsLabel: { fontSize: 11, color: "#8a9bc0", fontWeight: 700 },
  rsValue: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 13,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    gap: 4,
  },

  multRow: { padding: "5px 12px", borderBottom: "2px solid #0d1829" },
  multDisplay: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#0d1829",
    borderRadius: 8,
    padding: "6px 10px",
  },
  multChips: {
    background: "#3a7bd5",
    color: "#fff",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 14,
    padding: "4px 8px",
    borderRadius: 6,
    minWidth: 36,
    textAlign: "center",
  },
  multX: { color: "#ff6b6b", fontWeight: 900, fontSize: 18 },
  multMult: {
    background: "#e63946",
    color: "#fff",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 14,
    padding: "4px 8px",
    borderRadius: 6,
    minWidth: 36,
    textAlign: "center",
  },

  statsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 2,
    padding: "5px 12px",
    borderBottom: "2px solid #0d1829",
  },
  statBox: {
    background: "#0d1829",
    borderRadius: 6,
    padding: "6px 8px",
    textAlign: "center",
  },
  statLabel: {
    fontSize: 9,
    color: "#8a9bc0",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  statValHands: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 13,
    color: "#4ade80",
    marginTop: 2,
  },
  statValDiscards: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 13,
    color: "#fb923c",
    marginTop: 2,
  },

  moneyRow: {
    padding: "4px 12px",
    borderBottom: "2px solid #0d1829",
    textAlign: "center",
  },
  moneyVal: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 16,
    color: "#ffd700",
  },

  anteRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 2,
    padding: "5px 12px",
  },
  anteBox: {
    background: "#0d1829",
    borderRadius: 6,
    padding: "6px 8px",
    textAlign: "center",
  },
  anteLabel: { fontSize: 9, color: "#8a9bc0", fontWeight: 700 },
  anteVal: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 11,
    color: "#e2e8f0",
    marginTop: 2,
  },

  btnRunInfo: {
    margin: "5px 12px 3px",
    background: "#e63946",
    border: "none",
    borderRadius: 8,
    color: "#fff",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 8,
    padding: "8px",
    cursor: "pointer",
    letterSpacing: 1,
  },
  btnOptions: {
    margin: "3px 12px 8px",
    background: "#f59e0b",
    border: "none",
    borderRadius: 8,
    color: "#1a1a00",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 8,
    padding: "8px",
    cursor: "pointer",
    letterSpacing: 1,
  },

  // ── Main area ──
  mainArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    zIndex: 2,
    position: "relative",
    padding: "10px 16px 10px",
    overflow: "hidden",
  },

  // ── Top row: jokers + tarots ──
  topRow: {
    display: "flex",
    gap: 10,
    marginBottom: 6,
    alignItems: "flex-start",
  },
  jokersZone: {
    flex: 1,
    minHeight: 76,
    background: "rgba(0,0,0,0.25)",
    border: "2px dashed rgba(255,255,255,0.15)",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    padding: "8px 10px",
    gap: 8,
    position: "relative",
  },
  jokersLabel: {
    position: "absolute",
    top: 4,
    left: 8,
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 7,
    color: "rgba(255,255,255,0.3)",
    pointerEvents: "none",
  },
  jokerSlot: {
    width: 54,
    height: 62,
    background: "rgba(255,255,255,0.05)",
    border: "1.5px dashed rgba(255,255,255,0.15)",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,0.15)",
    fontSize: 20,
  },
  tarotsZone: {
    width: 140,
    minHeight: 76,
    background: "rgba(0,0,0,0.25)",
    border: "2px dashed rgba(255,255,255,0.15)",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px",
    gap: 8,
    position: "relative",
    flexShrink: 0,
  },
  tarotsLabel: {
    position: "absolute",
    top: 4,
    left: 8,
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 7,
    color: "rgba(255,255,255,0.3)",
    pointerEvents: "none",
  },
  tarotSlot: {
    width: 46,
    height: 62,
    background: "rgba(255,255,255,0.05)",
    border: "1.5px dashed rgba(255,255,255,0.15)",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,0.15)",
    fontSize: 18,
  },

  // ── Hand result ──
  handResultArea: {
    textAlign: "center",
    minHeight: 36,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  handName: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 13,
    color: "#ffd700",
    textShadow: "0 0 16px rgba(255,215,0,0.5)",
  },
  handScore: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 10,
    color: "#fff",
    marginTop: 4,
    opacity: 0.8,
  },

  // ── Cards ──
  cardsWrapper: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    paddingBottom: 40
  },
  cardsContainer: {
    display: "flex",
    gap: 18,
    alignItems: "flex-end",
    justifyContent: "center",
    flexWrap: "wrap",
  },

  cardBase: {
    width: 62,
    height: 90,
    background: "#fff",
    borderRadius: 8,
    border: "1.5px solid #ccc",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 5px",
    cursor: "pointer",
    position: "relative",
    userSelect: "none",
    boxShadow: "2px 3px 8px rgba(0,0,0,0.4)",
    transition: "transform 0.15s, box-shadow 0.15s",
  },
  cardSelected: { transform: "translateY(-16px)",
    
    boxShadow: "0 14px 28px rgba(0,0,0,0.6)",
    border: "2.5px solid #ffd700",
  },
  cardNormal: {
    transform: "translateY(0)",
  },
  cardCorner: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    lineHeight: 1,
    alignSelf: "flex-start",
  },
  cardCornerBottom: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    lineHeight: 1,
    alignSelf: "flex-end",
    transform: "rotate(180deg)",
  },
  cardRank: { fontSize: 13, fontWeight: 900, lineHeight: 1 },
  cardSuitSm: { fontSize: 10, lineHeight: 1 },
  cardCenter: { fontSize: 22 },
  cardRed: { color: "#cc0000" },
  cardBlack: { color: "#111" },

  // ── Deck back ──
  deckBack: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 78,
    height: 112,
    background: "#1a3a8f",
    borderRadius: 8,
    border: "2px solid #2a5ad4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 26,
    boxShadow: "2px 3px 8px rgba(0,0,0,0.5)",
  },
  deckCount: {
    position: "absolute",
    right: 0,
    bottom: -18,
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 7,
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
    width: 58,
  },

  // ── Actions ──
  actionsArea: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
  },
  handCountLabel: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 8,
    color: "rgba(255,255,255,0.35)",
  },
  actionsRow: {
    display: "flex",
    gap: 12,
    alignItems: "center",
  },

  btnPlay: (active) => ({
    background: "#2a6fd4",
    border: "2px solid #4a8fe4",
    borderRadius: 10,
    color: "#fff",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 9,
    padding: "12px 20px",
    cursor: active ? "pointer" : "default",
    letterSpacing: 1,
    opacity: active ? 1 : 0.45,
    transition: "opacity 0.15s",
  }),
  sortGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    alignItems: "center",
  },
  sortLabel: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 7,
    color: "rgba(255,255,255,0.4)",
  },
  sortBtns: { display: "flex", gap: 4 },
  btnSort: {
    background: "#ffd700",
    border: "2px solid #b8860b",
    borderRadius: 6,
    color: "#1a1a00",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 7,
    padding: "6px 10px",
    cursor: "pointer",
  },
  btnDiscard: (active) => ({
    background: active ? "#666" : "#444",
    border: `2px solid ${active ? "#999" : "#666"}`,
    borderRadius: 10,
    color: "#fff",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 9,
    padding: "12px 20px",
    cursor: active ? "pointer" : "default",
    letterSpacing: 1,
    opacity: active ? 1 : 0.45,
    transition: "opacity 0.15s",
  }),

  // ── Overlay ──
  overlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.75)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
  },
  overlayBox: {
    background: "#1a2340",
    border: "3px solid #ffd700",
    borderRadius: 16,
    padding: "32px 48px",
    textAlign: "center",
  },
  overlayTitle: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 18,
    color: "#ffd700",
    marginBottom: 4,
  },
  overlaySub: {
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 10,
    color: "#8a9bc0",
  },
  btnRestart: {
    marginTop: 20,
    background: "#2a6fd4",
    border: "2px solid #4a8fe4",
    borderRadius: 8,
    color: "#fff",
    fontFamily: "'Press Start 2P', monospace",
    fontSize: 8,
    padding: "10px 20px",
    cursor: "pointer",
  },
};